### PR TITLE
Added hostpad for wap.

### PR DESCRIPTION
**Pull request by tonybaltovski**
Currently works with static IP.

@TheDash

### CODE REVIEW

**Comment by TheDash** [comment]
This has been tested on the PR2 and confirmed to work?

**Comment by TheDash** [comment]
Waiting for confirmation that udev brings up wlan0.

**Comment by TheDash** [comment]
@tonybaltovski can this be merged? Does wlan0 get brought up now?

**Comment by tonybaltovski** [comment]
@TheDash  wlan0 is brought up.  Merge away.

**Pull request merged**
